# Generated by Django 5.0.3 on 2024-10-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='default_value', max_length=100, null=True)),
                ('on_leave', models.BooleanField(default=False)),
                ('has_msic', models.BooleanField(default=False)),
                ('has_white_card', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
