# Generated by Django 5.0.6 on 2024-10-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255)),
                ('job_count', models.PositiveIntegerField()),
                ('job_date', models.DateField()),
                ('trailer_type', models.CharField(choices=[('S', 'S'), ('SDL', 'SDL'), ('RT', 'RT'), ('BDBL', 'BDBL')], max_length=4)),
            ],
        ),
    ]
