# Generated by Django 5.0.6 on 2024-10-07 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_roster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roster',
            old_name='finish_date',
            new_name='job_date',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='driver_id',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='note',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='trailer_id',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='vehicle_id',
        ),
        migrations.AddField(
            model_name='roster',
            name='client_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='roster',
            name='construction_site',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='roster',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.driver'),
        ),
        migrations.AddField(
            model_name='roster',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roster',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roster',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roster',
            name='trailer1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trailer1', to='myapp.trailer'),
        ),
        migrations.AddField(
            model_name='roster',
            name='trailer2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trailer2', to='myapp.trailer'),
        ),
        migrations.AddField(
            model_name='roster',
            name='trailer3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trailer3', to='myapp.trailer'),
        ),
        migrations.AddField(
            model_name='roster',
            name='trailer_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='roster',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.vehicle'),
        ),
        migrations.AddField(
            model_name='roster',
            name='wharf_status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
